/**
 * Sync theme CSS import from openblog.config.ts → theme.generated.css
 */
import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

import { resolveThemeConfig } from "@openblog/core";
import { getThemeStylesheet } from "@openblog/themes";

const templateRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(templateRoot, "../..");
const inferenceFile = path.join(repoRoot, "integrations", "theme", ".generated", "inference.json");
const outFile = path.join(templateRoot, "src", "app", "theme.generated.css");

async function loadConfig() {
  const configPath = path.join(repoRoot, "openblog.config.ts");
  const mod = await import(pathToFileURL(configPath).href);
  return mod.default;
}

function loadInferredPreset(): string | undefined {
  if (!fs.existsSync(inferenceFile)) {
    return undefined;
  }

  try {
    const data = JSON.parse(fs.readFileSync(inferenceFile, "utf8")) as {
      suggestedPreset?: string;
    };
    return data.suggestedPreset;
  } catch {
    return undefined;
  }
}

async function main() {
  const config = await loadConfig();
  const inferred = loadInferredPreset();
  const resolved = resolveThemeConfig(config.theme, inferred as never);

  const importPath = getThemeStylesheet(resolved.preset);
  const colorModeClass =
    resolved.colorMode === "system"
      ? "ob-theme-system"
      : resolved.colorMode === "dark"
        ? "ob-theme-dark"
        : "ob-theme-light";

  const colorScheme =
    resolved.colorMode === "system"
      ? "light dark"
      : resolved.colorMode === "dark"
        ? "dark"
        : "light";

  const css = `@import "tailwindcss";
@import "${importPath}";

/* Auto-generated by scripts/sync-theme.ts — do not edit */
/* preset: ${resolved.preset} | colorMode: ${resolved.colorMode} */

:root {
  color-scheme: ${colorScheme};
}

html.${colorModeClass} {
  /* hook for preset-specific system/dark variants */
}
`;

  fs.writeFileSync(outFile, css, "utf8");
  console.log(`✓ Theme synced: ${resolved.preset} → ${outFile}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
